/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_transform_TransformXSL */

#ifndef _Included_org_xemeiah_transform_TransformXSL
#define _Included_org_xemeiah_transform_TransformXSL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_transform_TransformXSL
 * Method:    doTransform
 * Signature: (Lorg/xemeiah/dom/Element;Lorg/xemeiah/dom/Element;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_transform_TransformXSL_doTransform
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
