/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_CharacterData */

#ifndef _Included_org_xemeiah_dom_CharacterData
#define _Included_org_xemeiah_dom_CharacterData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_CharacterData
 * Method:    appendData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_CharacterData_appendData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xemeiah_dom_CharacterData
 * Method:    deleteData
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_CharacterData_deleteData
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_xemeiah_dom_CharacterData
 * Method:    getData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_CharacterData_getData
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_CharacterData
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_xemeiah_dom_CharacterData_getLength
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_CharacterData
 * Method:    insertData
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_CharacterData_insertData
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_xemeiah_dom_CharacterData
 * Method:    replaceData
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_CharacterData_replaceData
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     org_xemeiah_dom_CharacterData
 * Method:    setData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_CharacterData_setData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xemeiah_dom_CharacterData
 * Method:    substringData
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_CharacterData_substringData
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
