/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_Text */

#ifndef _Included_org_xemeiah_dom_Text
#define _Included_org_xemeiah_dom_Text
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_Text
 * Method:    isElementContentWhitespace
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_xemeiah_dom_Text_isElementContentWhitespace
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Text
 * Method:    replaceWholeText
 * Signature: (Ljava/lang/String;)Lorg/w3c/dom/Text;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Text_replaceWholeText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xemeiah_dom_Text
 * Method:    splitText
 * Signature: (I)Lorg/w3c/dom/Text;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Text_splitText
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
