/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_ProcessingInstruction */

#ifndef _Included_org_xemeiah_dom_ProcessingInstruction
#define _Included_org_xemeiah_dom_ProcessingInstruction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_ProcessingInstruction
 * Method:    getData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_ProcessingInstruction_getData
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_ProcessingInstruction
 * Method:    getTarget
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_ProcessingInstruction_getTarget
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_ProcessingInstruction
 * Method:    setData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_ProcessingInstruction_setData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
