/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_Attr */

#ifndef _Included_org_xemeiah_dom_Attr
#define _Included_org_xemeiah_dom_Attr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_Attr
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Attr_getName
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Attr
 * Method:    getValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Attr_getValue
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Attr
 * Method:    getNamespaceURI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Attr_getNamespaceURI
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Attr
 * Method:    setValue
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_Attr_setValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xemeiah_dom_Attr
 * Method:    isId
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_xemeiah_dom_Attr_isId
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
