/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_parser_XemParser */

#ifndef _Included_org_xemeiah_dom_parser_XemParser
#define _Included_org_xemeiah_dom_parser_XemParser
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
