/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_ChrootDocument */

#ifndef _Included_org_xemeiah_dom_ChrootDocument
#define _Included_org_xemeiah_dom_ChrootDocument
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
