__STARTNAMESPACE ( xem_pers, "http://www.xemeiah.org/ns/xem/persistence" ) 
  __KEY(name)
  __KEY(branchRevId)
  __KEY(fork)
  __KEY(commit)
  __KEY(merge)
  __KEY(drop)
  __KEY(reopen)
  __KEY(create_branch)
  __KEY(rename_branch)
  __KEY(get_current_branch_name)
  __KEY(get_current_branch_id)
  __KEY(get_current_revision_id)
  __KEY(get_current_branch_revision_id)
  __KEY(get_current_revision_writable)
  __KEY(get_current_forked_from)
  __KEY(get_branch_name)
  __KEY(get_branch_id)
  __KEY(get_branch_forked_from)
  __KEY(get_branches_tree)
  __KEY(lookup_revision)
__ENDNAMESPACE ( xem_pers, xem_pers );
