/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_Element */

#ifndef _Included_org_xemeiah_dom_Element
#define _Included_org_xemeiah_dom_Element
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_Element
 * Method:    triggerElementEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_Element_triggerElementEnd
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getNodeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Element_getNodeName
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getNamespaceURI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Element_getNamespaceURI
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getLocalName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Element_getLocalName
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getFirstChild
 * Signature: ()Lorg/xemeiah/dom/Element;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Element_getFirstChild
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getLastChild
 * Signature: ()Lorg/xemeiah/dom/Element;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Element_getLastChild
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getChildNodes
 * Signature: ()Lorg/xemeiah/dom/NodeList;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Element_getChildNodes
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getAttributeNS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Element_getAttributeNS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getAttributeNodeNS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/xemeiah/dom/Attr;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Element_getAttributeNodeNS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getElementsByTagNameNS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/xemeiah/dom/NodeList;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Element_getElementsByTagNameNS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    removeAttributeNode
 * Signature: (Lorg/w3c/dom/Attr;)Lorg/w3c/dom/Attr;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Element_removeAttributeNode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    setAttributeNS
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_Element_setAttributeNS
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    setAttributeNodeNS
 * Signature: (Lorg/w3c/dom/Attr;)Lorg/w3c/dom/Attr;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Element_setAttributeNodeNS
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    setIdAttributeNode
 * Signature: (Lorg/w3c/dom/Attr;Z)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_Element_setIdAttributeNode
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    appendChild
 * Signature: (Lorg/w3c/dom/Node;)Lorg/w3c/dom/Node;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Element_appendChild
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    getAttributes
 * Signature: ()Lorg/w3c/dom/NamedNodeMap;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Element_getAttributes
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Element
 * Method:    lookupNamespaceURI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Element_lookupNamespaceURI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
