/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_xpath_XPathExpression */

#ifndef _Included_org_xemeiah_dom_xpath_XPathExpression
#define _Included_org_xemeiah_dom_xpath_XPathExpression
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_xpath_XPathExpression
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_xpath_XPathExpression_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_xpath_XPathExpression
 * Method:    doEvaluateExpression
 * Signature: (Lorg/w3c/dom/Node;Ljava/util/Map;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_xpath_XPathExpression_doEvaluateExpression
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
