/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_xpath_XPathResult */

#ifndef _Included_org_xemeiah_dom_xpath_XPathResult
#define _Included_org_xemeiah_dom_xpath_XPathResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
