/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_CDATASection */

#ifndef _Included_org_xemeiah_dom_CDATASection
#define _Included_org_xemeiah_dom_CDATASection
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
