/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_NamedNodeMap */

#ifndef _Included_org_xemeiah_dom_NamedNodeMap
#define _Included_org_xemeiah_dom_NamedNodeMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_NamedNodeMap
 * Method:    getNamedItemNS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/w3c/dom/Node;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_NamedNodeMap_getNamedItemNS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_NamedNodeMap
 * Method:    removeNamedItemNS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/w3c/dom/Node;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_NamedNodeMap_removeNamedItemNS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_NamedNodeMap
 * Method:    setNamedItemNS
 * Signature: (Lorg/w3c/dom/Node;)Lorg/w3c/dom/Node;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_NamedNodeMap_setNamedItemNS
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
