/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_Node */

#ifndef _Included_org_xemeiah_dom_Node
#define _Included_org_xemeiah_dom_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_Node
 * Method:    getNextSibling
 * Signature: ()Lorg/w3c/dom/Node;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Node_getNextSibling
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
