/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_transform_TransformSerializer */

#ifndef _Included_org_xemeiah_transform_TransformSerializer
#define _Included_org_xemeiah_transform_TransformSerializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_transform_TransformSerializer
 * Method:    doSerialize
 * Signature: (Lorg/xemeiah/dom/Element;Ljava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_transform_TransformSerializer_doSerialize
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
