/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_DocumentFactory */

#ifndef _Included_org_xemeiah_dom_DocumentFactory
#define _Included_org_xemeiah_dom_DocumentFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_DocumentFactory_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    openVolatile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_DocumentFactory_openVolatile
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    format
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_DocumentFactory_format
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_DocumentFactory_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_DocumentFactory_close
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    releaseDocument
 * Signature: (Lorg/xemeiah/dom/Document;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_DocumentFactory_releaseDocument
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    createBranch
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_DocumentFactory_createBranch
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    newStandaloneDocument
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/xemeiah/dom/Document;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_DocumentFactory_newStandaloneDocument
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    newVolatileDocument
 * Signature: ()Lorg/xemeiah/dom/Document;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_DocumentFactory_newVolatileDocument
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    process
 * Signature: (Lorg/w3c/dom/Element;Lorg/w3c/dom/NodeList;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_DocumentFactory_process
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    isNamespaceAware
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_xemeiah_dom_DocumentFactory_isNamespaceAware
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_DocumentFactory
 * Method:    isValidating
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_xemeiah_dom_DocumentFactory_isValidating
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
