/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_transform_TransformParser */

#ifndef _Included_org_xemeiah_transform_TransformParser
#define _Included_org_xemeiah_transform_TransformParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_transform_TransformParser
 * Method:    doParse
 * Signature: (Ljava/io/InputStream;Lorg/xemeiah/dom/Element;)V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_transform_TransformParser_doParse
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
