/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_xpath_XPathEvaluator */

#ifndef _Included_org_xemeiah_dom_xpath_XPathEvaluator
#define _Included_org_xemeiah_dom_xpath_XPathEvaluator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_xpath_XPathEvaluator
 * Method:    createExpression
 * Signature: (Ljava/lang/String;Lorg/w3c/dom/xpath/XPathNSResolver;)Lorg/xemeiah/dom/xpath/XPathExpression;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_xpath_XPathEvaluator_createExpression
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
