/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_NodeList */

#ifndef _Included_org_xemeiah_dom_NodeList
#define _Included_org_xemeiah_dom_NodeList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_NodeList
 * Method:    getItem
 * Signature: (I)Lorg/xemeiah/dom/Node;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_NodeList_getItem
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
