/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xemeiah_dom_Document */

#ifndef _Included_org_xemeiah_dom_Document
#define _Included_org_xemeiah_dom_Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xemeiah_dom_Document
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_Document_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_Document_commit
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    reopen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_Document_reopen
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    merge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xemeiah_dom_Document_merge
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    createForkBranch
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Document_createForkBranch
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Document_toString
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    getBaseURI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_xemeiah_dom_Document_getBaseURI
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    createAttributeNS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/xemeiah/dom/Attr;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Document_createAttributeNS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    createCDATASection
 * Signature: (Ljava/lang/String;)Lorg/xemeiah/dom/CDATASection;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Document_createCDATASection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    createComment
 * Signature: (Ljava/lang/String;)Lorg/xemeiah/dom/Comment;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Document_createComment
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    createTextNode
 * Signature: (Ljava/lang/String;)Lorg/w3c/dom/Text;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Document_createTextNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    createElementNS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/w3c/dom/Element;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Document_createElementNS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    getDocumentElement
 * Signature: ()Lorg/xemeiah/dom/Element;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Document_getDocumentElement
  (JNIEnv *, jobject);

/*
 * Class:     org_xemeiah_dom_Document
 * Method:    getElementById
 * Signature: (Ljava/lang/String;)Lorg/w3c/dom/Element;
 */
JNIEXPORT jobject JNICALL Java_org_xemeiah_dom_Document_getElementById
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
